travis-ci: libevent-2.0.22 is now already installed
was causing :

$ if [ "$TRAVIS_OS_NAME" = "osx" -a "$PROJECT" = "miniupnpc-libevent" ]; then brew update > /dev/null && brew install libevent; fi
Error: libevent-2.0.22 already installed
To install this version, first `brew unlink libevent`